### ISSUE TITLE
Is there any example?

### ISSUE THREAD

**Issue by sevaru** [andrewrabon/little-web-dj#1]
It's interesting project.
But can you provide any example (maybe working app on gh-pages)?

**Comment by andrewrabon** [comment]
@sevaru Sorry for the late reply! I definitely need to redo my GitHub notifications setup.

I'll publish an "unrestricted" version on GH Pages this weekend. Sorry again and thanks for your interest in the project! :)

**Comment by sevaru** [comment]
@andrewrabon 
That's totally fine.
Thank you!
I'll wait :)

**Comment by andrewrabon** [comment]
Just an update: I have this setup on a test site, but it's not quite working yet. I'll be fixing it up later tonight and hopefully can release it then. :)

**Comment by andrewrabon** [comment]
Anyone should now be able to create an account and start making projects at [lsdj-test.firebaseapp.com](https://lsdj-test.firebaseapp.com/). 😊

Please remember this is alpha-quality software and a modern browser is needed to run it at this time (I haven't set up minification/bundling yet.) Further work is forthcoming.

**Comment by andrewrabon** [comment]
Actually there may be further work here... but the site is up. 😬

**Comment by sevaru** [comment]
That is exactly what i was looking to build by myself!
Glad you did that)

I would look more into when i come home!

For now i cant figure out the controls on the emulator's screen.

**Comment by andrewrabon** [comment]
Fixed some of the more obvious things and the core functionality, outside downloading .SAV's, is working. [Give it a shot.](https://lsdj-test.firebaseapp.com/)

Here's the keymap:

```
const KEY_MAP = {
  arrowup: 'up',
  arrowdown: 'down',
  arrowleft: 'left',
  arrowright: 'right',
  x: 'b',
  z: 'a',
  shift: 'select',
  enter: 'start',
};
```

For anyone out there: any help with the actual JS emulator would be really appreciated, as it's the other weak part of the thing -- it's pretty creaky and the audio part is especially janky. I have plans to fork the original repo and start working on a custom JS GB emulator based on it with modern APIs (and no globals) but that'll be an entirely separate project...

**Comment by sevaru** [comment]
Yeah keyboard now works pretty well, thanks)

Is there any tips/guides on how to run application locally?

I'm not a huge expert in emulation but i'd actually wanna participate in it)

**Comment by andrewrabon** [comment]
So, if you'd just like to run LSDj locally you can [grab the demo ROM](http://www.littlesounddj.com/lsd/latest/demo_version/) and pop it into an emulator of your choice.

If you'd like to run **this** project, I believe there are a couple steps:

1. [Sign up for a free Firebase account.](https://firebase.google.com/)
2. Create a Firebase project.
3. Under Databse, activate Cloud Firestore.
4. Under Authentication, enable Email/Password as a sign-in method.
5. Add the file `.firebaserc` to the project root (it's excluded from source control.) It should look like:

```
{
  "projects": {
    "default": "YOUR_PROJECT_ID"
  }
}
```

For instance the ID for the test site is "lsdj-test."

6. Install the Firebase Tools command line program.
7. cd to the project directory and run `firebase deploy`.

I haven't done a dry run of this, but it should be more or less what's needed. If there are snags along the way I'd love to help iron them out.

Let me know what you decide!

**Comment by andrewrabon** [comment]
Also, all this info is a great fit for the Readme, so I'll be adding it there soon. :)

**Comment by andrewrabon** [comment]
This seems to be taken care of. Let me know if there are any issues!
